#!/bin/bash
# //====================================================
# //	System Testing:Debian 12
# //	Author:	shan0h
# //	Dscription: Xray Menu Management
# //	email: shan0h34@gmail.com
# //  telegram: https://t.me/shan0h
# //====================================================
# // font color configuration | FEVERDREAM SSH AUTOSCRIPT
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER VLESS              $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${grenbo}1.${NC} \033[0;36mCreating a Vless Account${NC}"
echo -e "\033[1;93m│  ${grenbo}2.${NC} \033[0;36mDelete Vless Account${NC}"
echo -e "\033[1;93m│  ${grenbo}3.${NC} \033[0;36mRenew Vless Account${NC}"
echo -e "\033[1;93m│  ${grenbo}4.${NC} \033[0;36mCheck Vless Login Account${NC}"
echo -e "\033[1;93m│  ${grenbo}5.${NC} \033[0;36mCheck Vless Config Account${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 4 ] : " menu
case $menu in
1)
    add-vless
    ;;
2)
    del-vless
    ;;
3)
    renew-vless
    ;;
4)
    cek-vless
    ;;
5)
    user-vless
    ;;
*)
    menu
    ;;
esac
